### ISSUE TITLE
ansible-galaxy download : Content has no field named 'owner'

### ISSUE THREAD

**Issue by MaxiReglisse** [fiaasco/icinga2#6]
Hi,
several errors occured during ansible-galaxy download:

1) first error:

    `ansible-galaxy collection install fiaasco.icinga2`
    - downloading role 'collection', owned by  
     [WARNING]: - collection was NOT installed successfully: Content has no field named 'owner'

    ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.

2) second error:

    `ansible-galaxy collection install fiaasco.icinga2 --ignore-errors`
    - downloading role 'collection', owned by 
     [WARNING]: - collection was NOT installed successfully: Content has no field named 'owner'

    - downloading role 'icinga2', owned by fiaasco
     [WARNING]: - fiaasco.icinga2 was NOT installed successfully: - sorry, fiaasco.icinga2 was not found on https://galaxy.ansible.com.

Thanks in advance,

Ernest.

**Comment by stroobl** [comment]
Hi, I'm not able to reproduce this behaviour. Are you using ansible 2.9?

**Comment by MaxiReglisse** [comment]
I'm really sorry... but actually, with a version of ansible >=2.9, it worked very well.
